{% set version = "0.1" %}
{% set sha256 = "19b3d296d2dd9882d233d025ee6ba21b4b6cfe706d8fbd19603e3b9ffb08bb07" %}

package:
  name: mucor3
  version: {{ version }}

source:
  - url: https://github.com/blachlylab/mucor3/archive/master.zip
    sha256: 47e2555e49ff4b1c65309bdd217f115360706c89195d2beb50404c823b61a876

  - url: https://github.com/blachlylab/vcf_atomizer/archive/master.zip
    folder: vcf_atomizer
    sha256: 51fea9d8ae7447d76bd361f3e438a00120ee00a58b69268e2ff280d8d8a2a5d1

  - url: https://github.com/blachlylab/depthGauge/archive/master.zip
    folder: depthGauge
    sha256: 22311d3376615dbe2caaf0ac0f18862c07aafe2b5495a63085e244c3d761af4d

  - url: https://github.com/blachlylab/dhtslib/archive/v0.6.0.zip
    folder: depthGauge/dhtslib
    sha256: a7a2b2c19e8f90ed9f4735041d09b506cffe19c0880ec0fee928bf21ab780c8e

build:
  number: 0
  skip: False
  entry_points:
    - mucor3 = mucor.mucor:main

requirements:
  build:
    - autoconf
    - automake
    - go-cgo
    - ldc
    - htslib
    - {{ compiler('c') }}
  host:
    - python >=3
  run:
    - python >=3
    - ldc
    - pandas
    - jq
    - htslib

test:
  imports:
    - mucor
  commands:
    - mucor3 -h
    - depthgauge -h
    - atomizer



about:
  home: https://github.com/blachlylab/mucor3
  license: BSD
  summary: Aggregation of VCF data into useful spreadsheets.
