{% set version = "0.2" %}

package:
  name: mucor3
  version: {{ version }}

source:
  - url: https://github.com/blachlylab/mucor3/archive/v0.2.tar.gz
    sha256: e890de2086bcd465856f134ff08c0279fe47a157961a75a358c59bcb7d002353

  - url: https://github.com/blachlylab/vcf_atomizer/archive/v0.2.tar.gz
    folder: vcf_atomizer
    sha256: a62f31839f2798dec2f3c4ee04f239122ab816ec1ec09a9eb0ead7ad4f7e593b

  - url: https://github.com/blachlylab/depthGauge/archive/v0.1.tar.gz
    folder: depthGauge
    sha256: ffc169681a4c6b51c4a4e7df13ccf7d43610651bb4d7dd881dc737f8a28bbe1d

  - url: https://github.com/blachlylab/dhtslib/archive/v0.6.0.tar.gz
    folder: depthGauge/dhtslib
    sha256: 385221f09b26c211373bf52f9803101c3a409df8b81b591e4f9cec41a9c7991d

build:
  number: 0
  skip: False
  entry_points:
    - mucor3 = mucor.mucor:main

requirements:
  build:
    - autoconf
    - automake
    - go-cgo
    - ldc
    - htslib
    - {{ compiler('c') }}
  host:
    - python >=3
  run:
    - python >=3
    - ldc
    - pandas
    - jq
    - htslib

test:
  imports:
    - mucor
  commands:
    - mucor3 -h
    - depthgauge -h
    - vcf_atomizer



about:
  home: https://github.com/blachlylab/mucor3
  license: BSD
  summary: Aggregation of VCF data into useful spreadsheets.
