{% set version = "0.1" %}
{% set sha256 = "19b3d296d2dd9882d233d025ee6ba21b4b6cfe706d8fbd19603e3b9ffb08bb07" %}

package:
  name: mucor3
  version: {{ version }}

source:
  - url: https://github.com/blachlylab/mucor3/archive/v0.1.tar.gz
    sha256: 8b236de6ec1435e5d82241a9acb7ce0063036282992b273550bed039ae4b7a3d

  - url: https://github.com/blachlylab/vcf_atomizer/archive/v0.1.tar.gz
    folder: vcf_atomizer
    sha256: 349ceab5e369f9c439d8c16ea067b01b5958e25f8aec24ef8f2ae927f7399d94

  - url: https://github.com/blachlylab/depthGauge/archive/v0.1.tar.gz
    folder: depthGauge
    sha256: ffc169681a4c6b51c4a4e7df13ccf7d43610651bb4d7dd881dc737f8a28bbe1d

  - url: https://github.com/blachlylab/dhtslib/archive/v0.6.0.tar.gz
    folder: depthGauge/dhtslib
    sha256: 385221f09b26c211373bf52f9803101c3a409df8b81b591e4f9cec41a9c7991d

build:
  number: 0
  skip: False
  entry_points:
    - mucor3 = mucor.mucor:main

requirements:
  build:
    - autoconf
    - automake
    - go-cgo
    - ldc
    - htslib
    - {{ compiler('c') }}
  host:
    - python >=3
  run:
    - python >=3
    - ldc
    - pandas
    - jq
    - htslib

test:
  imports:
    - mucor
  commands:
    - mucor3 -h
    - depthgauge -h
    - vcf_atomizer



about:
  home: https://github.com/blachlylab/mucor3
  license: BSD
  summary: Aggregation of VCF data into useful spreadsheets.
